hash1 = {1=>2,2=>3,3=>4}
list1 = [1,2,3]
exp1 = 2**3
false_var= !true
a_neg = -2
a_positive = +3
multiply_num = 3*2
divide_num = 3/2 #1.5
mod_num = 4%3
bitwise_left_shift = 0xFFFFFF>>1 #0x7fffff
bitwise_right_shift =0xFFFFFF<<1 #0x1fffffe
bitwise_and = 0xFFFFFF /\ 0xFFFFFF # 0xFFFFFF
bitwise_xor = 0xFFFFFF ^ 0xFFFFFF #0x0
bitwise_or = 0xFFFFFF \/ 0xFFFFFF #0xFFFFFF
less_than = 1 < 2 #true
less_than_eq = 1 <= 2 #true
greater_than_eq = 1 >= 2 #true
greater_than = 2>1 #true



